---
title: "Network Analysis and STEM Education"
subtitle: "A Brief Introduction & Demo"
author: "Dr. Joshua Rosenberg, University of Tennessee, Knoxville"
institute: "The LASER Institute"
date: "2021/08/11 (updated: `r Sys.Date()`)"
output:
  xaringan::moon_reader:
    css:
       - default
       - css/laser.css
       - css/laser-fonts.css
    lib_dir: libs
    seal: false
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      slideNumberFormat: |
         <div class="progress-bar-container">
          <div class="progress-bar" style="width: calc(%current% / %total% * 100%);">
          </div>
         </div>
---
class: clear, title-slide, inverse, center, top, middle

# `r rmarkdown::metadata$title`
## `r rmarkdown::metadata$subtitle`
### `r rmarkdown::metadata$author`
###  2021/08/11 (updated: `r Sys.Date()`)

---
# Agenda: Two parts

1. Brief overview of network analysis (15 min.)
2. Walkthrough of a network analysis learning lab (25 min.)

---

class: clear, inverse, center, middle

# 1. Short presentation

---

# 1. Overview

--
1. Why use network analysis?
1. **What** is network analysis exactly?
1. What are **common techniques** used for network analysis? 
1. What are some of the **technical and ethical considerations**? 
1. How is network analysis **used in STEM education** research? 

---
class: clear, inverse, center, middle

# 1.1. Why network anaylsis?

---

# Networks matter

- We're often influenced by our networks
    - Josh’s friend Ryan Estrellado sharing about Ted Lasso on Slack
    - Bret caring about ethical issues in social media research
    - Seeing how colleagues negotiate speaking up in a department meeting
    - TikTok dance competitions
- Or, in a multi-level context, how factors at other levels, like teacher practice, matter
- But, our research often examines individuals and their characteristics and antecedents (READ FRANK 1998)
- Network analysis treats the relationships between people as a phenomenon of central interest

.footnote[
Krumm, A., Means, B., & Bienkowski, M. (2018). [Learning analytics goes to school: A collaborative approach to improving education.](https://www.taylorfrancis.com/books/mono/10.4324/9781315650722/learning-analytics-goes-school-andrew-krumm-barbara-means-marie-bienkowski) Routledge.
]

---
class: clear, inverse, center, middle

# 1.2. What is network analysis exactly?

---

# Network analysis is about relationships

- We can think of network analysis as a broad range of tools for examining relationships but it's helpful to be concrete
    - visualizing networks through sociograms
    - describing networks through the use of individual or network statistics
    - using network models for key processes, such as selection and influence

.footnote[
Krumm, A., Means, B., & Bienkowski, M. (2018). [Learning analytics goes to school: A collaborative approach to improving education.](https://www.taylorfrancis.com/books/mono/10.4324/9781315650722/learning-analytics-goes-school-andrew-krumm-barbara-means-marie-bienkowski) Routledge.
]

---
class: clear, inverse, center, middle

# 1.3. What are common techniques used for quantifying text? 

---

# Collecting and Creating Data

- asking people about who they relate with (ref the AERA Open piece, ref the SITE piece)
- studying networks through traces (bodong, JRST)
- for visualizing networks, R is great and open-source and free
    - tidygraph and ggraph are great for these purposes (find example?)

---

# Describing Networks

- for describing networks, using descriptive stats can get one far (coburn paper)

---

# Modeling Networks

- for selection and influence, we have many options
    - selection
        - logistic regression
        - p2 MLM selection model
        - latent space selection
        - ergm selection model
    - influence
        - regression
        - multi-level
        - latent space
        
---

class: clear, inverse, center, middle

# 1.4. What are some of the technical and ethical considerations of text mining? 

---

#  Ethics Matter

- ensuring a high response rate when using self-report - building trust with schools/a network
- privacy/sensitivity - not depicting individuals' names in networks
- sharing data / balancing open science and privacy
- going beyond IRB with respect to using digital traces

---
class: clear, inverse, center, middle

# 1.5. How is text mining used in STEM education research?

---

# Applications in STEM Ed Research

- visualization: XXX

---

# Applications in STEM Ed Research

- descriptive: coburn piece, SITE piece

---

# Applications in STEM Ed Research

- selection and influence: AERA Open piece, JRST piece, bodong piece

---

# Walkthrough

Let's head over to the `aera-workshop` project in RStudio Cloud to start the walkthrough.

Click on `sna-demo.Rmd` to begin!
